### ISSUE TITLE
Failed to register structures:

### ISSUE THREAD

**Issue by MeisterWolo** [MCTCP/TerrainControl#308]
Hey guys,! hopefully I'm just wrong and only got some problems with finding the right versions, but i got this error concerning TC.

Pastebin: http://pastebin.com/079RXWta

[16:08:16] [Server thread/INFO]: [TerrainControl] Enabling TerrainControl v2.6.2
[16:08:16] [Server thread/INFO]: [TerrainControl] [INFO] 0 Global custom objects loaded
[16:08:16] [Server thread/FATAL]: [TerrainControl] [FATAL] Failed to register structures:
[16:08:16] [Server thread/FATAL]: [TerrainControl] [FATAL] java.lang.NoSuchMethodException: net.minecraft.world.gen.structure.MapGenStructureIO.b(java.lang.Class, java.lang.String)
	at java.lang.Class.getDeclaredMethod(Unknown Source)
	at com.khorn.terraincontrol.bukkit.TCPlugin.onEnable(TCPlugin.java:97)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:459)
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:172)
	at net.minecraft.world.World.<init>(World.java:350)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:153)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
	at java.lang.Thread.run(Unknown Source)

Best regards,
Wolo

**Comment by rutgerkok** [comment]
Closing this, as it simply looks like the wrong version of TC is being used.
