### ISSUE TITLE
TC 2.6.4 with latest Spigot fails on /mv create

### ISSUE THREAD

**Issue by spektre1** [MCTCP/TerrainControl#322]
I tried following the beginner's tutorial and ran:
/mv create world_name NORMAL -s 12 -g TerrainControl

It spits out in my server console:
[16:39:50 WARN]: net.minecraft.server.v1_8_R1.ReportedException: Exception generating new chunk
[16:39:50 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:148)
[16:39:50 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
[16:39:50 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:95)
[16:39:50 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.createWorld(CraftServer.java:920)
[16:39:50 WARN]: 	at org.bukkit.Bukkit.createWorld(Bukkit.java:463)
[16:39:50 WARN]: 	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
[16:39:50 WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:421)
[16:39:50 WARN]: 	at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:229)
[16:39:50 WARN]: 	at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[16:39:50 WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[16:39:50 WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[16:39:50 WARN]: 	at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[16:39:50 WARN]: 	at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:894)
[16:39:50 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:39:50 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:39:50 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[16:39:50 WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[16:39:50 WARN]: 	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[16:39:50 WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[16:39:50 WARN]: 	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[16:39:50 WARN]: 	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[16:39:50 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[16:39:50 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[16:39:50 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696)
[16:39:50 WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[16:39:50 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634)
[16:39:50 WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537)
[16:39:50 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[16:39:50 WARN]: Caused by: java.lang.NullPointerException
[16:39:50 WARN]: 	at com.khorn.terraincontrol.bukkit.generator.TCChunkGenerator.generateExtBlockSections(TCChunkGenerator.java:89)
[16:39:50 WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.generator.CustomChunkGenerator.getOrCreateChunk(CustomChunkGenerator.java:53)
[16:39:50 WARN]: 	at net.minecraft.server.v1_8_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:140)
[16:39:50 WARN]: 	... 27 more

Please let me know if i can provide further debugging info.

**Comment by spektre1** [comment]
Scratch this. The 2.7.0 build I found on jenkins works without the errors. Sorry.
