### ISSUE TITLE
Update class reference for Spigot 1.8.3

### ISSUE THREAD

**Issue by PikachuEXE** [MCTCP/TerrainControl#324]
Hi dear author, thank you for writing this plugin :D

Just want to notify you the new Spigot version for 1.8.3 is released, so some references needs to be updated ;)

Thanks again!

I also got some error logs below, hope it helps!

## Error logs
Plugin Version: `2.6.4`
Spigot version: Compiled with their Build Tool 35
### When plugin loads
```
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/WorldGenFactory
	at com.khorn.terraincontrol.bukkit.TCPlugin.onEnable(TCPlugin.java:97) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:200) [spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_11]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.WorldGenFactory
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.3.jar:git-Spigot-fcb68de-1e56438]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_11]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_11]
	... 9 more
```
### When the world loads
```
[11:54:37] [Server thread/INFO]: [TerrainControl] [INFO] Starting to enable world ''galaxy__resource_planet__lv1''...
[11:54:37] [Server thread/WARN]: [Multiverse-Core] Failed to set the generator for world 'galaxy__resource_planet__lv1' to 'TerrainControl': java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/WorldProvider
[11:54:37] [Server thread/WARN]: [Multiverse-Core] This is a bug in the generator plugin, NOT a bug in Multiverse!
```

**Comment by rutgerkok** [comment]
You can use [the latest dev build](http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/default/) for now. A release will be uploaded very soon.

**Comment by rutgerkok** [comment]
Proper release is uploaded to spigotmc.org, so I'm closing this issue.
