### ISSUE TITLE
Chromaticraft (Server Specific) Crash (World Generation?)

### ISSUE THREAD

**Issue by Fazerio** [MCTCP/TerrainControl#376]
Here's the Crash report:
----------------------------------------
[11:19:23] [Server thread/INFO]: Starting minecraft server version 1.7.10
[11:21:20] [Server thread/INFO]: Loading properties
[11:21:20] [Server thread/INFO]: Default game type: SURVIVAL
[11:21:20] [Server thread/INFO]: Generating keypair
[11:21:20] [Server thread/INFO]: Starting Minecraft server on *:25565
[11:23:59] [Server thread/INFO]: Preparing level "world"
[11:24:00] [Server thread/WARN]: Unable to find spawn biome
[11:24:01] [Server thread/WARN]: Unable to find spawn biome
[11:24:12] [Server thread/WARN]: Unable to find spawn biome
[11:24:13] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception getting block type in world
	at net.minecraft.world.World.<init>(World.java:275) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) ~[mt.class:?]
	at net.minecraft.world.WorldServerMulti.<init>(WorldServerMulti.java:14) ~[mm.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:222) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NullPointerException
	at Reika.ChromatiCraft.World.DungeonGenerator.tryGenerate(DungeonGenerator.java:130) ~[DungeonGenerator.class:?]
	at Reika.ChromatiCraft.World.DungeonGenerator.generate(DungeonGenerator.java:72) ~[DungeonGenerator.class:?]
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) ~[GameRegistry.class:?]
	at Reika.ChromatiCraft.Auxiliary.ChromaAux.interceptChunkPopulation(ChromaAux.java:55) ~[ChromaAux.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) ~[ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
	at net.minecraft.world.World.func_147437_c(World.java:365) ~[ahb.class:?]
	at net.minecraft.world.World.func_147474_b(World.java:329) ~[ahb.class:?]
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71) ~[aqo.class:?]
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:749) ~[mt.class:?]
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715) ~[mt.class:?]
	at net.minecraft.world.World.<init>(World.java:260) ~[ahb.class:?]
	... 6 more
------------------------------------------------------------

This only happens when generating a new world specifically on a server, if I copy over a single-player world, it runs fine.

**Comment by rutgerkok** [comment]
> ```
Caused by: java.lang.NullPointerException
 at Reika.ChromatiCraft.World.DungeonGenerator.tryGenerate(DungeonGenerator.java:130) ~[DungeonGenerator.class:?]
```

At a first glance, it looks like a bug in ChromatiCraft. At least I don't see any sign of TerrainControl in your log.

**Comment by Fazerio** [comment]
That's true, it's something to do with the original generation. Like I've stated already, if i take a pre-made world, and generate new chunks, it runs entirely fine.

**Comment by rutgerkok** [comment]
> At a first glance, it looks like a bug in ChromatiCraft
> That's true, it's something to do with the original generation.

Yeah, but this is the bug tracker of TerrainControl, I cannot fix bugs in ChromatiCraft.
