### ISSUE TITLE
1.9 Support & PerWorldPlugins

### ISSUE THREAD

**Issue by TheChampTF** [MCTCP/TerrainControl#392]
00:19:35] [Server thread/ERROR]: Error occurred while enabling TerrainControl v2.7.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/WorldGenFactory
	at com.khorn.terraincontrol.bukkit.TCPlugin.onEnable(TCPlugin.java:88) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:141) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522) [spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.WorldGenFactory
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.jar:git-Spigot-7d15d07-c194444]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]

**Comment by Martyn96** [comment]
I'm wondering, why does TerrainControl need to use NMS to function @rutgerkok @Timethor ? What is missing from the CraftBukkit/Spigot API?

**Comment by rutgerkok** [comment]
I'm closing this, as the builds available on the [build server](http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/default/) work on Minecraft 1.9.
