### ISSUE TITLE
can't create new world + world corrupt?

### ISSUE THREAD

**Issue by aycgit** [MCTCP/TerrainControl#401]
when i try to create a world using the terraingenerator multiverse generator i get this error:

[09:06:25] [Server thread/INFO]: Wereld2003 issued server command: /mv create survival2 normal -g TerrainControl
[09:06:25] [Server thread/INFO]: [TerrainControl] Starting to enable world ''test''...
[09:06:25] [Server thread/INFO]: [TerrainControl] 0 world custom objects loaded.
[09:06:25] [Server thread/INFO]: [TerrainControl] 62 biomes Loaded
[09:06:25] [Server thread/INFO]: Wereld2003: Starting creation of world 'survival2'...
[09:06:25] [Server thread/INFO]: [TerrainControl] Starting to enable world ''survival2''...
[09:06:33] [Server thread/INFO]: [TerrainControl] 886 world custom objects loaded.
[09:06:34] [Server thread/FATAL]: [TerrainControl] Duplicate biome id 375 (Plains and TemperatePlains)!
[09:06:34] [Server thread/FATAL]: [TerrainControl] The biome TemperatePlains has been prevented from loading.
[09:06:34] [Server thread/INFO]: [TerrainControl] If you are updating an old pre-Minecraft 1.7 world, please read this wiki page:
[09:06:34] [Server thread/INFO]: [TerrainControl] https://github.com/Wickth/TerrainControl/wiki/Upgrading-an-old-map-to-Minecraft-1.7
[09:06:34] [Server thread/FATAL]: [TerrainControl] Duplicate biome id 401 (Mesa and Mesa Small M)!
[09:06:34] [Server thread/FATAL]: [TerrainControl] The biome Mesa Small M has been prevented from loading.
[09:06:34] [Server thread/INFO]: [TerrainControl] If you are updating an old pre-Minecraft 1.7 world, please read this wiki page:
[09:06:34] [Server thread/INFO]: [TerrainControl] https://github.com/Wickth/TerrainControl/wiki/Upgrading-an-old-map-to-Minecraft-1.7
[09:06:34] [Server thread/FATAL]: [TerrainControl] Duplicate biome id 287 (Jungle and JungleLowlands)!
[09:06:34] [Server thread/FATAL]: [TerrainControl] The biome JungleLowlands has been prevented from loading.
[09:06:34] [Server thread/INFO]: [TerrainControl] If you are updating an old pre-Minecraft 1.7 world, please read this wiki page:
[09:06:34] [Server thread/INFO]: [TerrainControl] https://github.com/Wickth/TerrainControl/wiki/Upgrading-an-old-map-to-Minecraft-1.7
[09:06:34] [Server thread/FATAL]: [TerrainControl] Duplicate biome id 342 (Cold Taiga and ColdForestFirThicketEdge)!
[09:06:34] [Server thread/FATAL]: [TerrainControl] The biome ColdForestFirThicketEdge has been prevented from loading.
[09:06:34] [Server thread/INFO]: [TerrainControl] If you are updating an old pre-Minecraft 1.7 world, please read this wiki page:
[09:06:34] [Server thread/INFO]: [TerrainControl] https://github.com/Wickth/TerrainControl/wiki/Upgrading-an-old-map-to-Minecraft-1.7
[09:06:34] [Server thread/WARN]: java.lang.NullPointerException: The validated object is null
[09:06:34] [Server thread/WARN]:    at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
[09:06:34] [Server thread/WARN]:    at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
[09:06:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.RegistrySimple.a(SourceFile:34)
[09:06:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.RegistryMaterials.a(SourceFile:22)
[09:06:34] [Server thread/WARN]:    at com.khorn.terraincontrol.bukkit.CustomBiome.createInstance(CustomBiome.java:97)
[09:06:34] [Server thread/WARN]:    at com.khorn.terraincontrol.bukkit.BukkitBiome.forCustomBiome(BukkitBiome.java:43)
[09:06:34] [Server thread/WARN]:    at com.khorn.terraincontrol.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:87)
[09:06:34] [Server thread/WARN]:    at com.khorn.terraincontrol.configuration.WorldSettings.readSettings(WorldSettings.java:262)
[09:06:34] [Server thread/WARN]:    at com.khorn.terraincontrol.configuration.WorldSettings.loadBiomes(WorldSettings.java:147)
[09:06:34] [Server thread/WARN]:    at com.khorn.terraincontrol.configuration.WorldSettings.loadSettings(WorldSettings.java:80)
[09:06:34] [Server thread/WARN]:    at com.khorn.terraincontrol.configuration.WorldSettings.<init>(WorldSettings.java:67)
[09:06:34] [Server thread/WARN]:    at com.khorn.terraincontrol.bukkit.TCPlugin.getDefaultWorldGenerator(TCPlugin.java:140)
[09:06:34] [Server thread/WARN]:    at org.bukkit.WorldCreator.getGeneratorForName(WorldCreator.java:311)
[09:06:34] [Server thread/WARN]:    at org.bukkit.WorldCreator.generator(WorldCreator.java:183)
[09:06:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldManager.java:240)
[09:06:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.commands.CreateCommand.runCommand(CreateCommand.java:114)
[09:06:34] [Server thread/WARN]:    at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[09:06:34] [Server thread/WARN]:    at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[09:06:34] [Server thread/WARN]:    at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[09:06:34] [Server thread/WARN]:    at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:906)
[09:06:34] [Server thread/WARN]:    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[09:06:34] [Server thread/WARN]:    at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98)
[09:06:34] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[09:06:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350)
[09:06:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185)
[09:06:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[09:06:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[09:06:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[09:06:34] [Server thread/WARN]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[09:06:34] [Server thread/WARN]:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09:06:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[09:06:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
[09:06:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[09:06:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[09:06:34] [Server thread/WARN]:    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[09:06:34] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)

the things on top are me doing the command  and then i get double biome id errors but they dont matter becouse i use a biome pack and i dont need all the biomes but the validated object is null error looks like a problem for me and i cant generate a new world
this also happened when i tried to create a new world after my old one got corrupted:
![2016-04-18_15 13 11](https://cloud.githubusercontent.com/assets/13834197/14605619/ba644968-0579-11e6-9ea1-13efadbef1d3.png)
![2016-04-18_15 13 25](https://cloud.githubusercontent.com/assets/13834197/14605626/c03ef1da-0579-11e6-9745-005a10a54b8f.png)
when i joined the server one day i saw it and the map turned into a non-tc world

**Comment by rutgerkok** [comment]
Interesting, but based on just the error I cannot see what went wrong. I need some way to reproduce the issue.

Could you send the TerrainControl config files for this world? (You can post them here, or send them by e-mail, address is on my Github profile.)

**Comment by aycgit** [comment]
the terrain thing looks like an out of memory error stopping tc from generating

**Comment by rutgerkok** [comment]
Could be, but there's not much that I can do as long as I can't reproduce the error myself.

**Comment by 100photos** [comment]
I have the same problem, using the biomebundle pack. I don't know what's causing it

**Comment by 100photos** [comment]
This is me doing 'mv generators'
[19:05:47 INFO]: [Multiverse-Core] PLEASE IGNORE the 'Plugin X does not contain any generators' message below!
[19:05:47 INFO]: [TerrainControl] Starting to enable world ''world''...
[19:05:57 INFO]: [TerrainControl] 1232 world custom objects loaded.
[19:05:57 WARN]: java.lang.NullPointerException: The validated object is null
[19:05:57 WARN]: at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
[19:05:57 WARN]: at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
[19:05:57 WARN]: at net.minecraft.server.v1_9_R1.RegistrySimple.a(SourceFile:34)
[19:05:57 WARN]: at net.minecraft.server.v1_9_R1.RegistryMaterials.a(SourceFile:22)
[19:05:57 WARN]: at com.khorn.terraincontrol.bukkit.CustomBiome.createInstance(CustomBiome.java:97)
[19:05:57 WARN]: at com.khorn.terraincontrol.bukkit.BukkitBiome.forCustomBiome(BukkitBiome.java:43)
[19:05:57 WARN]: at com.khorn.terraincontrol.bukkit.BukkitWorld.createBiomeFor(BukkitWorld.java:87)
[19:05:57 WARN]: at com.khorn.terraincontrol.configuration.WorldSettings.readSettings(WorldSettings.java:262)
[19:05:57 WARN]: at com.khorn.terraincontrol.configuration.WorldSettings.loadBiomes(WorldSettings.java:147)
[19:05:57 WARN]: at com.khorn.terraincontrol.configuration.WorldSettings.loadSettings(WorldSettings.java:80)
[19:05:57 WARN]: at com.khorn.terraincontrol.configuration.WorldSettings.<init>(WorldSettings.java:67)
[19:05:57 WARN]: at com.khorn.terraincontrol.bukkit.TCPlugin.getDefaultWorldGenerator(TCPlugin.java:140)
[19:05:57 WARN]: at com.onarandombox.MultiverseCore.commands.GeneratorCommand.runCommand(GeneratorCommand.java:44)
[19:05:57 WARN]: at com.pneumaticraft.commandhandler.multiverse.CommandHandler.checkAndRunCommand(CommandHandler.java:279)
[19:05:57 WARN]: at com.pneumaticraft.commandhandler.multiverse.CommandHandler.processFoundCommands(CommandHandler.java:143)
[19:05:57 WARN]: at com.pneumaticraft.commandhandler.multiverse.CommandHandler.locateAndRunCommand(CommandHandler.java:93)
[19:05:57 WARN]: at com.onarandombox.MultiverseCore.MultiverseCore.onCommand(MultiverseCore.java:906)
[19:05:57 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:05:57 WARN]: at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98)
[19:05:57 WARN]: at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[19:05:57 WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.APIWrapperMethods.runCommand(APIWrapperMethods.java:616)
[19:05:57 WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.APIWrapperMethods.runCommand(APIWrapperMethods.java:620)
[19:05:57 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:05:57 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:05:57 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:05:57 WARN]: at java.lang.reflect.Method.invoke(Method.java:497)
[19:05:57 WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:170)
[19:05:57 WARN]: at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:94)
[19:05:57 WARN]: at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftFuture.run(CraftFuture.java:89)
[19:05:57 WARN]: at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[19:05:57 WARN]: at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
[19:05:57 WARN]: at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[19:05:57 WARN]: at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[19:05:57 WARN]: at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[19:05:57 WARN]: at java.lang.Thread.run(Thread.java:745)
[19:05:57 INFO]: An internal error occurred when attempting to perform this command.

**Comment by aycgit** [comment]
1: really? Closed?
2: @100photos that is something appart from this issue
