### ISSUE TITLE
BufferedImage overloaded when loading large image file.

### ISSUE THREAD

**Issue by sync667** [MCTCP/TerrainControl#413]
Hello, i use last at this moment TC version 138 and Spigot 1465. We try to generate world bigger then 100k x 100k. So we prepared image png that have about 10MB. And TC can't handle that because of int max value.

Full error log:
`[21:34:04] [Server thread/INFO]: -------- World Settings For [new2] --------
[21:34:04] [Server thread/INFO]: Mob Spawn Range: 4
[21:34:04] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[21:34:04] [Server thread/INFO]: Cactus Growth Modifier: 100%
[21:34:04] [Server thread/INFO]: Cane Growth Modifier: 100%
[21:34:04] [Server thread/INFO]: Melon Growth Modifier: 100%
[21:34:04] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[21:34:04] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[21:34:04] [Server thread/INFO]: Sapling Growth Modifier: 100%
[21:34:04] [Server thread/INFO]: Wheat Growth Modifier: 100%
[21:34:04] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[21:34:04] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[21:34:04] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[21:34:04] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[21:34:04] [Server thread/INFO]: Random Lighting Updates: false
[21:34:04] [Server thread/INFO]: Structure Info Saving: true
[21:34:04] [Server thread/INFO]: Max Entity Collisions: 8
[21:34:04] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[21:34:04] [Server thread/INFO]: Max TNT Explosions: 100
[21:34:04] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:34:04] [Server thread/INFO]: Item Despawn Rate: 6000
[21:34:04] [Server thread/INFO]: Item Merge Radius: 2.5
[21:34:04] [Server thread/INFO]: Arrow Despawn Rate: 1200
[21:34:04] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: false
[21:34:04] [Server thread/INFO]: View Distance: 10
[21:34:04] [Server thread/INFO]: Zombie Aggressive Towards Villager: false
[21:34:04] [Server thread/INFO]: Experience Merge Radius: 3.0
[21:34:04] [Server thread/FATAL]: [TerrainControl] Cannot properly reflect biome manager, falling back on BiomeMode:Normal
[21:34:04] [Server thread/FATAL]: [TerrainControl] java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.khorn.terraincontrol.generator.biome.BiomeModeManager.create(BiomeModeManager.java:73)
	at com.khorn.terraincontrol.generator.biome.BiomeModeManager.createCached(BiomeModeManager.java:92)
	at com.khorn.terraincontrol.bukkit.BukkitWorld.enable(BukkitWorld.java:670)
	at com.khorn.terraincontrol.bukkit.TCPlugin.onWorldInit(TCPlugin.java:184)
	at com.khorn.terraincontrol.bukkit.generator.TCChunkGenerator.makeSureWorldIsInitialized(TCChunkGenerator.java:42)
	at com.khorn.terraincontrol.bukkit.generator.TCChunkGenerator.getDefaultPopulators(TCChunkGenerator.java:68)
	at net.minecraft.server.v1_9_R1.WorldServer.b(WorldServer.java:115)
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.createWorld(CraftServer.java:893)
	at org.bukkit.Bukkit.createWorld(Bukkit.java:468)
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:261)
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:421)
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:402)
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:377)
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:676)
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:310)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411)
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376)
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331)
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269)
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Array size > Integer.MAX_VALUE!
	at javax.imageio.ImageTypeSpecifier.createBufferedImage(ImageTypeSpecifier.java:1081)
	at javax.imageio.ImageReader.getDestination(ImageReader.java:2896)
	at com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1280)
	at com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1577)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)
	at com.khorn.terraincontrol.generator.biome.layers.LayerFromImage.<init>(LayerFromImage.java:39)
	at com.khorn.terraincontrol.generator.biome.layers.LayerFactory.createFromImage(LayerFactory.java:55)
	at com.khorn.terraincontrol.generator.biome.FromImageBiomeGenerator.initLayers(FromImageBiomeGenerator.java:21)
	at com.khorn.terraincontrol.generator.biome.LayeredBiomeGenerator.<init>(LayeredBiomeGenerator.java:21)
	at com.khorn.terraincontrol.generator.biome.FromImageBiomeGenerator.<init>(FromImageBiomeGenerator.java:15)
	... 30 more

[21:34:04] [Server thread/INFO]: [TerrainControl] World new2 is now enabled!
[21:34:04] [Server thread/INFO]: Preparing start region for level 1 (Seed: -7722955172920740941)
[21:34:05] [Server thread/INFO]: [TerrainControl] [Debug] Already enabled for ''new2''
[21:34:05] [Server thread/INFO]: [TerrainControl] Starting to enable world ''new''...
[21:34:32] [Server thread/INFO]: [TerrainControl] 1570 world custom objects loaded.`

We must get it working so we are ready to help with coding fix for that if needed.
Thanks for help :)

**Comment by sync667** [comment]
I think the easiest way to handle that would be use many png files and add only proper data quota to generator or use library for png that can handle bigger files.

**Comment by rutgerkok** [comment]
Your image is uncompressed bigger than 4GB, so TC cannot load it. As you said, we would need to split up the image.

Keep in mind that each pixel is 4x4 blocks, so an image of 2000x2000 pixels will already spawn 8000x8000 blocks.

**Comment by sync667** [comment]
@rutgerkok It's any way that we can do it? Yea of course we know long time ago that 4x4 is 1x1px ;) but we want to develop one of the most biggest worlds in MC in size more then 100k x 100k blocks.

**Comment by rutgerkok** [comment]
Theoretically, yes, but I'm not going to code it. It's a lot of work, it will make the image reading code of TerrainControl much more complicated (so more difficult to maintain), etc. It will also only be useful to very few people.

**Comment by sync667** [comment]
So maybe any tool to connect many that big parts in one map? Any machine will handle that or it's much to do to get it working.

**Comment by rutgerkok** [comment]
Connecting two worlds is easy: just pick the .mca files in the region folder that you want and put them in one world. Generating the right mca files is the difficult part; you'd need to cut up the image into smaller parts, and generate worlds based on the smaller images. Maybe splitting up the image into four [quadrants](https://commons.wikimedia.org/wiki/File:Cartesian_coordinates_2D.svg) will work?
