### ISSUE TITLE
[1.9.4] Error

### ISSUE THREAD

**Issue by Emalton** [MCTCP/TerrainControl#424]
Stacktrace:
`[20:32:58] [Server thread/ERROR]: Error occurred while enabling TerrainControl v2.8.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R1/WorldGenFactory
at com.khorn.terraincontrol.bukkit.TCPlugin.onEnable(TCPlugin.java:88) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:201) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R1.WorldGenFactory
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-23da8b0]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
... 9 more`

**Comment by JfromHolland** [comment]
@Emalton there is currently no Terrain Control version for 1.9.4 (there's worked on), use 2.8.1 for 1.9.2

**Comment by Emalton** [comment]
Oh okay.

Thank you.

**Comment by rutgerkok** [comment]
You can help testing the 1.9.4 version [here](http://build.mctcp.com/job/TerrainControl%20-%20Master%20-%20Gradle/140/default/). Use the file terraincontrol-bukkit-2.8.1-SNAPSHOT.jar .
