### ISSUE TITLE
NoSuchMethodException: MapGenStructureIO

### ISSUE THREAD

**Issue by Edisoni** [MCTCP/TerrainControl#456]
Server: Thermos 1.7.10(Fork KCauldron)

[10:15:27 INFO]: [TerrainControl] Enabling TerrainControl v2.7.0-SNAPSHOT
[10:15:28 INFO]: [TerrainControl] [INFO] 0 Global custom objects loaded
[10:15:28 FATAL]: [TerrainControl] [FATAL] Failed to register structures:
[10:15:28 FATAL]: [TerrainControl] [FATAL] java.lang.NoSuchMethodException: net.minecraft.world.gen.structure.MapGenS
tructureIO.b(java.lang.Class, java.lang.String)
        at java.lang.Class.getDeclaredMethod(Class.java:2130)
        at com.khorn.terraincontrol.bukkit.TCPlugin.onEnable(TCPlugin.java:92)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
        at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463)
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138)
        at net.minecraft.world.World.<init>(World.java:374)
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:162)
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
        at java.lang.Thread.run(Thread.java:745)

[10:15:28 INFO]: [TerrainControl] [INFO] Global objects loaded, waiting for worlds to load

**Comment by rutgerkok** [comment]
Maybe version [2.6.3](https://github.com/MCTCP/TerrainControl/wiki/Version-history#tc-2-6-3) works?

In any case, I'm not going to fix a bug for such an old version of Minecraft.
