### ISSUE TITLE
FATAL Error while running v2.8.2 Bukkit on Thermos 1.7.10 58

### ISSUE THREAD

**Issue by chezpaul** [MCTCP/TerrainControl#468]
Hey there, 
I'm running a 1.7.10 Thermos server with Terrain Control 2.8.2 Bukkit SNAPSHOT.
I get this error when loading plugin:
[14:23:11 INFO]: [TerrainControl] Enabling TerrainControl v2.8.2-SNAPSHOT
[14:23:11 INFO]: [TerrainControl] 22 Global custom objects loaded
[14:23:11 FATAL]: [TerrainControl] Failed to register structures:
[14:23:11 FATAL]: [TerrainControl] java.lang.NullPointerException

[14:23:11 ERROR]: Error occurred while enabling TerrainControl v2.8.2-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
[14:23:11 INFO]: [Vault] Enabling Vault v1.5.6-b49

Full server log: http://pastebin.com/Kjg0pYvF

**Comment by chezpaul** [comment]
Okay.... TC 2.8.2 is not for 1.7.10.
So what's the latest for 1.7.10? Is it 2.6.3?
There's so many bugs in that version. It's really too bad you don't update a 1.7.10 branch.  ;-(

**Comment by chezpaul** [comment]
The only version that works is the 2.6.3 from the bukkit site (which loads as 2.7.0 btw).
It's the only version that will let me create a world in multiverse but this world will have [immense pics](https://www.dropbox.com/s/zg5me17qisi3x31/2016-10-20_11.50.18.png?dl=0) in it.
I tried 2.6.2, "real" 2.6.3, 2.7.0 and 2.8.2.
I'm running a Thermos 1614.58 server with the latest Jenkins Multiverse 2.5

**Comment by chezpaul** [comment]
This is what I get in server condole log when I boot up with 2.6.3 from bucket site.

`[14:00:32 INFO]: [TerrainControl] Enabling TerrainControl v2.7.0-SNAPSHOT
[14:00:33 INFO]: [TerrainControl] [INFO] 0 Global custom objects loaded
[14:00:33 FATAL]: [TerrainControl] [FATAL] Failed to register structures:
[14:00:33 FATAL]: [TerrainControl] [FATAL] java.lang.NoSuchMethodException: net.minecraft.world.gen.structure.MapGenStructureIO.b(java.lang.Class, java.lang.String)
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at com.khorn.terraincontrol.bukkit.TCPlugin.onEnable(TCPlugin.java:92)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463)
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138)
	at net.minecraft.world.World.<init>(World.java:374)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
	at java.lang.Thread.run(Thread.java:745)

[14:00:33 INFO]: [TerrainControl] [INFO] Global objects loaded, waiting for worlds to load`

**Comment by MCPitman** [comment]
Just tried it myself and it looks to be a problem with Thermos. 1.7.10 is 2.5 years old so it's no surprise it is no longer being updated.

Try standard Spigot (or forge) 1.7.10 or alternatively, update to the latest version (1.10).

**Comment by chezpaul** [comment]
Thermos main guy is asking this:

"The author(s) of TerrainControl do not print the stacktrace when they encounter an exception -- they simply output the exception class. That needs to be changed for us to see where the problem occurred."

Is anyone interested here?

**Comment by rutgerkok** [comment]
I'm closing this issue, as Minecraft 1.7.10 is unsupported by us. TerrainControl 2.8.2 simply isn't going to work on it.
