### ISSUE TITLE
Mineshafts causing crashes in 1.10.2 forge

### ISSUE THREAD

**Issue by MCPitman** [MCTCP/TerrainControl#497]
http://pastebin.com/i9Hatbm3

I have not yet narrowed down if this is caused by all mineshafts or only the new Mesa styled ones. Will report back when I do.

Tagging @bloodmc in case this is related to the recent forge refactor.

**Comment by Helbirden** [comment]
Seconded.

http://pastebin.com/T7uqmSga

**Comment by mindcloud69** [comment]
Same error here

**Comment by Tokeli** [comment]
Is there a potential workaround for this until it's located- like a way to disable mineshafts entirely?

**Comment by MCPitman** [comment]
@Tokeli 

[Here](https://www.reddit.com/r/biomebundle/comments/5lvaeh/for_anyone_getting_crashes_related_to_bbundle/)

**Comment by croftyraider** [comment]
I've seen this too. For me, it was coming back from the nether that tripped it up, so the stack trace is a bit different:

`java.lang.NullPointerException: Exception preparing structure feature
	at com.khorn.terraincontrol.forge.generator.structure.MineshaftGen.func_75047_a(MineshaftGen.java:24)
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:37)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:27)
	at com.khorn.terraincontrol.forge.generator.ChunkProvider.func_180514_a(ChunkProvider.java:137)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
`

The implication here is that the chunks were already generated. Also, there was no crashing when I was originally wandering around a bit before starting my base.

**Comment by MCPitman** [comment]
Just done some more testing on this issue and have reproduced it with 100% success rate on returning from the nether to previously generated chunks. I get the same stacktrace as @croftyraider 

It happens in both virtual and non virtual biomes and can be avoided if mineshafts are disabled entirely in the worldconfig. The crash occurs with both Mineshaft generation types, 'normal' or 'mesa'.
