### ISSUE TITLE
1.12.1 crash

### ISSUE THREAD

**Issue by andris155** [MCTCP/TerrainControl#540]
```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 8/3/17 11:45 PM
Description: Exception ticking world

java.lang.NoSuchMethodError: net.minecraft.server.v1_12_R1.TileEntity.a(Lnet/minecraft/server/v1_12_R1/NBTTagCompound;)V
	at com.khorn.terraincontrol.bukkit.BukkitWorld.attachMetadata(BukkitWorld.java:943)
	at com.khorn.terraincontrol.customobjects.bo3.RandomBlockFunction.spawn(RandomBlockFunction.java:131)
	at com.khorn.terraincontrol.customobjects.bo3.BO3.spawnForced(BO3.java:186)
	at com.khorn.terraincontrol.customobjects.CustomObjectCoordinate.spawnWithChecks(CustomObjectCoordinate.java:68)
	at com.khorn.terraincontrol.customobjects.CustomObjectStructure.spawnForChunk(CustomObjectStructure.java:100)
	at com.khorn.terraincontrol.generator.resource.CustomStructureGen.spawnInChunk(CustomStructureGen.java:76)
	at com.khorn.terraincontrol.generator.resource.Resource.process(Resource.java:153)
	at com.khorn.terraincontrol.generator.ObjectSpawner.populate(ObjectSpawner.java:112)
	at com.khorn.terraincontrol.bukkit.generator.TXBlockPopulator.populate(TXBlockPopulator.java:25)
	at net.minecraft.server.v1_12_R1.Chunk.a(Chunk.java:1064)
	at net.minecraft.server.v1_12_R1.Chunk.loadNearby(Chunk.java:1020)
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.originalGetChunkAt(ChunkProviderServer.java:200)
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:167)
	at net.minecraft.server.v1_12_R1.PlayerChunk.a(PlayerChunk.java:121)
	at net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:179)
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:324)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:897)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Shenlong55** [comment]
Seeing a similar issue here.  Also on 1.12.1 with latest TC build (#179).

[crash-2017-08-13_00.28.02-server.txt](https://github.com/MCTCP/TerrainControl/files/1226318/crash-2017-08-13_00.28.02-server.txt)

**Comment by bloodmc** [comment]
dupe #537
